# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-state-platform-lab"
    dynamodb_table = "terraform-state-locks"
    encrypt        = true
    key            = "production/eks/terraform.tfstate"
    region         = "us-east-2"
  }
}
